context:
  name: azure-mgmt-rdbms
  version: 10.2.0b17
  u_name: azure_mgmt_rdbms

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/${{ name }}/${{ u_name }}-${{ version }}.tar.gz
    sha256: d679d1932af8226efd07b0c3a86cff14eacf013a05686844f9aeebe5b64cb8e4

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1

tests:
  - python:
      imports:
        - azure.mgmt.rdbms
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/Azure/azure-sdk-for-python
  summary: 'This is the Microsoft Azure RDBMS Management Client Library.'
  description: |
    This is the Microsoft Azure RDBMS Management Client Library.
  license: MIT
  license_file: LICENSE
  documentation: https://azure.github.io/azure-sdk-for-python
  repository: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
    - MementoRC
